### ISSUE TITLE
Couchapp adds %5C to the start of every file

### ISSUE THREAD

**Issue by mwmwmw** [mikeal/node.couchapp.js#39]
After creating a new couchapp boiler, and pushing it to the server, I kept getting "file not found" errors. 

I figured (and still do) that this is a virgin couch problem.. but I was able to sort out that the reason why the files were not found was because there was an escaped HTML "\" in the filename.

so if I typed in host:5984\myapp_design\myapp\index.html  // file not founderror

http://dev.thumperdaffodil.com/couch/2.jpg

if I added a %5c to the url, I'd get the file

host:5984\myapp_design\myapp\%5cindex.html // works

http://dev.thumperdaffodil.com/couch/1.jpg

I'm using the latest version of Node (0.6.7) and the most recent version of Couchapp (0.9.0) and CouchDB version 1.1.1

Any thoughts?

**Comment by yblee85** [comment]
at line of 185, where next line of     f = f.replace(att.root, att.prefix || '');

if (f[0] == '/') f = f.slice(1)

==> 
if (f[0] === '/' || f[0] === '\\\\') f = f.slice(1)

for some machines f[0] is '\\\\'
